# Generated by Django 5.2.2 on 2025-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wetlandsite',
            options={'ordering': ['-is_ramsar_site', 'name'], 'verbose_name': 'Wetland Site', 'verbose_name_plural': 'Wetland Sites'},
        ),
        migrations.AddField(
            model_name='wetlandsite',
            name='is_ramsar_site',
            field=models.BooleanField(default=False, verbose_name='Site Ramsar'),
        ),
    ]
